**Dropena and fillna**

In [1]:
import pandas as pd
var = pd.read_csv("F:\\panda_jupyter\\emp1.csv")
var

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198.0,Donald,OConnell,DOCONNEL,650.507.9833,21-Jun-07,SH_CLERK,2600.0,-,124,50.0
1,199.0,Douglas,Grant,DGRANT,650.507.9844,13-Jan-08,SH_CLERK,2600.0,-,124,50.0
2,200.0,Jennifer,Whalen,JWHALEN,515.123.4444,17-Sep-03,AD_ASST,4400.0,-,101,10.0
3,201.0,Michael,Hartstein,MHARTSTE,515.123.5555,17-Feb-04,MK_MAN,13000.0,-,100,20.0
4,202.0,Pat,Fay,PFAY,603.123.6666,17-Aug-05,MK_REP,6000.0,-,201,20.0
5,203.0,Susan,Mavris,SMAVRIS,515.123.7777,7-Jun-02,HR_REP,6500.0,-,101,40.0
6,204.0,Hermann,Baer,HBAER,515.123.8888,7-Jun-02,PR_REP,NaN,-,101,70.0
7,205.0,Shelley,Higgins,SHIGGINS,515.123.8080,7-Jun-02,AC_MGR,12008.0,-,101,110.0
8,206.0,William,Gietz,WGIETZ,515.123.8181,7-Jun-02,AC_ACCOUNT,8300.0,-,205,110.0
9,100.0,Steven,King,SKING,515.123.4567,17-Jun-03,AD_PRES,24000.0,-,-,90.0
10,101.0,Neena,Kochhar,NKOCHHAR,515.123.4568,21-Sep-05,AD_VP,17000.0,-,100,90.0
11,102.0,Lex,De Haan,LDEHAAN,515.123.4569,NaN,AD_VP,NaN,-,100,90.0
12,103.0,Alexander,NaN,AHUNOLD,590.423.4567,3-Jan-06,IT_PROG,9000.0,-,102,60.0
13,104.0,Bruce,Ernst,BERNST,590.423.4568,21-May-07,IT_PROG,6000.0,-,103,60.0
14,105.0,David,Austin,DAUSTIN,590.423.4569,25-Jun-05,IT_PROG,4800.0,-,103,60.0
15,106.0,Valli,Pataballa,VPATABAL,590.423.4560,5-Feb-06,IT_PROG,4800.0,-,103,60.0
16,107.0,Diana,Lorentz,DLORENTZ,590.423.5567,7-Feb-07,IT_PROG,4200.0,-,103,60.0
17,108.0,Nancy,Greenberg,NGREENBE,515.124.4569,17-Aug-02,FI_MGR,12008.0,-,101,100.0
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,110.0,John,Chen,JCHEN,515.124.4269,28-Sep-05,FI_ACCOUNT,8200.0,-,108,100.0
20,111.0,Ismael,Sciarra,ISCIARRA,515.124.4369,30-Sep-05,FI_ACCOUNT,7700.0,-,108,100.0
21,112.0,Jose Manuel,Urman,JMURMAN,515.124.4469,7-Mar-06,FI_ACCOUNT,7800.0,-,108,100.0
22,113.0,Luis,Popp,LPOPP,515.124.4567,7-Dec-07,FI_ACCOUNT,6900.0,-,108,100.0
23,114.0,Den,Raphaely,DRAPHEAL,515.127.4561,7-Dec-02,PU_MAN,11000.0,-,100,30.0
24,115.0,Alexander,Khoo,AKHOO,515.127.4562,18-May-03,PU_CLERK,3100.0,-,114,30.0

In [2]:
#var.dropna()

In [3]:
var.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]