In [1]:
import numpy as np
import pandas as pd

In [2]:
dict1 = {
    "name":["rahul", "rohit", "ritesh", "rakesh"],
    "marks": [92,34,24,17],
    "city" : ["delhi", "varansi", "kolkata", "dolakhpur"]
}

In [3]:
df = pd.DataFrame(dict1)

In [4]:
df

     name  marks       city
0   rahul     92      delhi
1   rohit     34    varansi
2  ritesh     24    kolkata
3  rakesh     17  dolakhpur

In [5]:
df.to_csv('friends.csv')

In [6]:
df.to_csv('friends_index_false.csv', index=False)

In [7]:
df.head(2)

    name  marks     city
0  rahul     92    delhi
1  rohit     34  varansi

In [8]:
df.tail(2)

     name  marks       city
2  ritesh     24    kolkata
3  rakesh     17  dolakhpur

In [10]:
df.describe()

          marks
count   4.00000
mean   41.75000
std    34.21866
min    17.00000
25%    22.25000
50%    29.00000
75%    48.50000
max    92.00000

In [ ]:
dhruv= pd.read_csv(